
##environment
spring:
  profiles:
    active: dev
  banner:
    location: banner.txt

# 配置mapper.xml位置，这个位置可以在pom.xml里配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    banner: false